name: CI - Build and Deploy Sample Application
run-name: Building and deploying Sample Application
on:
  workflow_dispatch:
jobs:
  setup-docker-host:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          ref: kar/dev
          path: k8s-dry-run
      - name: Debug OIDC Token Claims
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            const payload = token.split('.')[1];
            // Decode the base64 payload of the JWT
            const decoded = Buffer.from(payload, 'base64').toString('utf8');
            console.log("=== EXACT CLAIMS GITHUB IS SENDING TO AWS ===");
            console.log(JSON.stringify(JSON.parse(decoded), null, 2));
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::303417979872:role/github-oidc-admin-role
          aws-region: ap-south-1
