name: Destroy CI Setup
run-name: Destroying CI Setup
on:
  workflow_dispatch:
jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Hello World
        run: echo "Hello World"
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          ref: kar/dev
          path: k8s-dry-run
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::303417979872:role/github-oidc-admin-role
          aws-region: ap-south-1
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
      - name: Initialize and validate terraform
        run: |
          terraform init
          terraform validate
        working-directory: k8s-dry-run/terraform/docker-host
      - name: Destroy infrastructure
        run: terraform destroy -auto-approve
        working-directory: k8s-dry-run/terraform/docker-host